---
title: "05_WillowTimeModel"
format: html
editor: visual
---

# Willow Ptarmigan Time Removal Model

## Clear workspace

```{r}
# Clean your workspace to reset your R environment
rm( list = ls() )
# Check that you are in the right project folder
getwd()
```

## Library

```{r}
library(unmarked)
library(raster)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(AICcmodavg)
```

## Import data

```{r}
allCovs_std <- read.csv("E:/gyrf_analysis/MSgyrfalcon/wipt_final_df_28Dec23.csv")
allCovs_std <- allCovs_std[,c(-1)]
```

## Set area

Add as a column to the dataframe

```{r}
# the surveyed area was a 400 m radius circle

allCovs_std$area <- 400^2*pi/10000

```

## Model Frame

```{r}
timeFrame <- unmarkedFrameMPois(
  # import time removal columns(counts):
  y = allCovs_std[,c(2:6)], 
  siteCovs = data.frame(allCovs_std), 
  # define pifun type: 
  type = "removal" )
# fit models: multinomPois order of formulas: detection, abundance

```

## Time Removal Model

```{r}
time.model <- multinomPois( ~ 1 + julian + min_after_sun + wind + observer ~ 1 + tundra + tussock + tallshrub + elev + offset(log(area)), data = timeFrame)


model_summary <- summary(time.model)
```
